name: Build README

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository.
        uses: actions/checkout@v1
      - name: Setup Node.js 16.x.
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Cache Node dependencies to improve performance.
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Generate README.md from template.
        run: npm start
      - name: Commit and push new README.md to the repository.
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}